### PR TITLE
Add starter code for the campsite information API query-fetch

### PR DESCRIPTION
**Pull request by Todd-Kridel**

### CODE REVIEW

**Comment by Todd-Kridel** [comment]
Code was added and modified to/in the JavaScript file and the HTML file and the CSS file. The non-full-width of the background image of the main page continues to be an issue which now is also preventing the full-width display of the new display section that is for campsite information. But that background image situation should be an easy fix. :)

**Comment by Todd-Kridel** [comment]
We are doing a great effort and achieving a great start to our project!

**Comment by Todd-Kridel** [comment]
UPDATE: I now found a CSS setting addition that will correct the full-width problem that my display section was experiencing. But I continue to be inspecting about the setting problem that is occurring in the page navigation bar.

**Review by MaxTribble — APPROVED** [review]
Great job Todd!

**Pull request merged**
